# 個人的にコードの一貫性を重視しているためflutter_lintsから変更
include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    public_member_api_docs: false
