name: github_viewer
description: "This is a code check task for Flutter engineers employment in YUMEMI."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  dio: ^5.4.2+1
  dynamic_color: ^1.7.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.1
  github_colour: ^3.2.1
  go_router: ^13.2.2
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  nil: ^1.1.1
  retrofit: ^4.1.0
  riverpod_annotation: ^2.3.5

dev_dependencies:
  build_runner: ^2.4.9
  build_verify: ^3.1.0
  custom_lint: ^0.6.4
  flutter_test:
    sdk: flutter
  freezed: ^2.5.0
  go_router_builder: ^2.4.1
  http_mock_adapter: ^0.6.1
  mockito: ^5.4.4
  network_image_mock: ^2.1.1
  retrofit_generator: ^8.1.0
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
