name: Analyze and Test
on:
  push:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - name: Cache build_runner
        uses: actions/cache@v2
        with:
          path: '**/.dart_tool/build'
          key: build-runner-${{ hashFiles('**/asset_graph.json') }}-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: build-runner-
      - name: Get dependencies
        run: flutter pub get
      - name: Exec build_runner
        run: dart pub run build_runner build
      - name: Format
        run: dart format --output=none --set-exit-if-changed .
      - name: Analyze
        run: flutter analyze
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - name: Cache build_runner
        uses: actions/cache@v2
        with:
          path: '**/.dart_tool/build'
          key: build-runner-${{ hashFiles('**/asset_graph.json') }}-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: build-runner-
      - name: Get dependencies
        run: flutter pub get
      - name: Exec build_runner
        run: dart pub run build_runner build
      - name: Run tests
        run: flutter test
